// Generated by CoffeeScript 1.3.3
(function() {
  var _class;

  Jsl.Matrix = (function() {

    function Matrix() {
      return _class.apply(this, arguments);
    }

    Matrix.prototype.m = [];

    _class = (Matrix.m = []);

    return Matrix;

  })();

  Jsl.matrix = new Jsl.Matrix();

}).call(this);
