// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, fs;

  fs = require("fs");

  express = require("express");

  app = express();

  app.use(express["static"](__dirname));

  app.get("/", function(req, res) {
    res.header("Content-Type", "text/xml");
    return res.sendfile('index.svg');
  });

  app.listen(3000);

}).call(this);
